#line 2 "scanner.c"

#line 4 "scanner.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 1
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yynoreturn yy_fatal_error (yyconst char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 56
#define YY_END_OF_BUFFER 57
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[479] =
    {   0,
        0,    0,   57,   55,    1,    1,   42,   55,   30,   55,
       55,   19,   20,   28,   31,   44,   32,   55,   29,   52,
       45,   43,   37,   41,   38,   47,   23,   46,   24,   27,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   21,   55,   22,   29,   36,    0,   48,    0,
       39,    0,   25,    0,   52,   26,   50,    0,    0,   52,
        0,   33,   35,   34,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   14,   47,   47,   47,   47,   47,
       47,   47,   40,    0,   49,    0,   50,   52,   50,    0,
        0,   52,    0,   51,   47,   47,   47,   47,   47,   47,

       47,   47,   13,   47,   47,   47,   47,   47,   47,   47,
       47,    0,   53,    0,   52,   50,   54,   52,   51,   47,
       47,   10,   47,    4,   11,   47,   47,   47,   47,   47,
       47,   47,   17,    9,   47,    0,   52,   50,   52,   51,
       47,    2,   47,   12,    5,   47,   47,   15,   47,   47,
       18,   52,   50,   52,   51,   47,   47,   47,   47,   16,
        7,   52,   50,   52,   51,   47,    3,   47,    6,   52,
       50,   52,   51,   47,    8,   52,   50,   52,   51,   47,
       52,   50,   52,   51,   47,   52,   50,   52,   51,   47,
       52,   50,   52,   51,   47,   52,   50,   52,   51,   47,

       52,   50,   52,   51,   47,   52,   50,   52,   51,   47,
       52,   50,   52,   51,   47,   52,   50,   52,   51,   47,
       52,   50,   52,   51,   47,   52,   50,   52,   51,   47,
       52,   50,   52,   51,   47,   52,   50,    0,   51,   47,
        0,   51,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,

       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,

       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    1,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,    1,    1,   25,   25,   25,   25,   26,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       27,   28,   29,   30,   31,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,   25,   25,   41,   25,   42,
       43,   44,   25,   45,   46,   47,   48,   49,   50,   25,
       51,   25,   52,   53,   54,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[55] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    4,    1,
        1,    1,    1,    1,    4,    4,    1,    5,    1,    1,
        6,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[741] =
    {   0,
        0,  546,  561, 1016, 1016, 1016,  535,   48, 1016,  546,
        0, 1016, 1016, 1016,   42, 1016,   41,  533,  536,   45,
     1016, 1016,  523,  520,  517,    0, 1016, 1016, 1016, 1016,
       18,  494,  495,  490,   36,   28,  483,  489,  475,  474,
      473,  474, 1016,  457, 1016,   54, 1016,   62, 1016,  504,
     1016,  494, 1016,  482,   56, 1016,   59,  485,  476,   63,
       67, 1016, 1016, 1016,    0,  447,  442,  443,  451,  434,
      436,  431,  426,  426,    0,  418,  422,  412,  411,  405,
      410,  407, 1016,  441, 1016,  431,  419,   74,  416,  419,
       74,   77,  410,  407,    0,  391,  377,  376,  369,  375,

      362,  373,    0,  368,  363,  354,  345,  350,  351,  349,
      340,  375, 1016,  365,   81,  353,  356,   85,  347,    0,
      312,    0,  324,    0,    0,  321,  307,  304,  310,  298,
      297,  297,    0,    0,  300,  323,   88,  311,   89,  308,
        0,    0,  292,    0,    0,  281,  282,    0,  273,  274,
        0,   93,  290,   97,  287,    0,  261,  257,  252,    0,
        0,  100,  275,  101,  272,    0,    0,  246,    0,  105,
      266,  109,  263,    0,    0,  112,  260,  113,  257,    0,
      117,  254,  121,  251,    0,  124,  248,  125,  245,    0,
      129,  242,  133,  236,    0,  136,  224,  137,  218,    0,

      141,  212,  145,  201,    0,  148,  200,  149,  199,    0,
      153,  197,  157,  196,    0,  160,  195,  161,  194,    0,
      165,  193,  169,  191,    0,  172,   90,  173,   82,    0,
      177,   78,  181,   69,    0,  184, 1016,  185,   55,    0,
      189, 1016,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0, 1016, 1016,  221,  224,
      226,  230,  235,  238,  244,  248,  250,  254,  256,  259,
      262,  265,  268,  271,  274,  277,  280,  283,  286,  289,

      292,  295,  298,  301,  304,  307,  310,  313,  316,  319,
      322,  325,  328,  331,  334,  337,  340,  343,  346,  349,
      352,  355,  358,  361,  364,  367,  370,  373,  376,  379,
      382,  385,  388,  391,  394,  397,  400,  403,  406,  409,
      412,  415,  418,  421,  424,  427,  430,  433,  436,  439,
      442,  445,  448,  451,  454,  457,  460,  463,  466,  469,
      472,  475,  478,  481,  484,  487,  490,  493,  496,  499,
      502,  505,  508,  511,  514,  517,  520,  523,  526,  529,
      532,  535,  538,  541,  544,  547,  550,  553,  556,  559,
      562,  565,  568,  571,  574,  577,  580,  583,  586,  589,

      592,  595,  598,  601,  604,  607,  610,  613,  616,  619,
      622,  625,  628,  631,  634,  637,  640,  643,  646,  649,
      652,  655,  658,  661,  664,  667,  670,  673,  676,  679,
      682,  685,  688,  691,  694,  697,  700,  703,  706,  709,
      712,  715,  718,  721,  724,  727,  730,  733,  736,  739,
      742,  745,  748,  751,  754,  757,  760,  763,  766,  769,
      772,  775,  778,  781,  784,  787,  790,  793,  796,  799,
      802,  805,  808,  811,  814,  817,  820,  823,  826,  829,
      832,  835,  838,  841,  844,  847,  850,  853,  856,  859,
      862,  865,  868,  871,  874,  877,  880,  883,  886,  889,

      892,  895,  898,  901,  904,  907,  910,  913,  916,  919,
      922,  925,  928,  931,  934,  937,  940,  943,  946,  949,
      952,  955,  958,  961,  964,  967,  970,  973,  976,  979,
      982,  985,  988,  991,  994,  997, 1000, 1003, 1006, 1009
    } ;

static yyconst flex_int16_t yy_def[741] =
    {   0,
      478,    1,  478,  478,  478,  478,  478,  479,  478,  478,
      480,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  481,  478,  478,  478,  478,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  478,  478,  478,  478,  478,  479,  478,  479,
      478,  482,  478,  478,  478,  478,  478,  483,  478,  478,
      478,  478,  478,  478,  484,  484,  484,  484,  484,  484,
      484,  484,  484,  484,  484,  484,  484,  484,  484,  484,
      484,  484,  478,  485,  478,  486,  478,  478,  478,  483,
      483,  478,  478,  478,  487,  487,  487,  487,  487,  487,

      487,  487,  487,  487,  487,  487,  487,  487,  487,  487,
      487,  485,  478,  488,  478,  478,  483,  478,  478,  489,
      489,  489,  489,  489,  489,  489,  489,  489,  489,  489,
      489,  489,  489,  489,  489,  478,  478,  478,  478,  478,
      490,  490,  490,  490,  490,  490,  490,  490,  490,  490,
      490,  478,  478,  478,  478,  491,  491,  491,  491,  491,
      491,  478,  478,  478,  478,  492,  492,  492,  492,  478,
      478,  478,  478,  493,  493,  478,  478,  478,  478,  494,
      478,  478,  478,  478,  495,  478,  478,  478,  478,  496,
      478,  478,  478,  478,  497,  478,  478,  478,  478,  498,

      478,  478,  478,  478,  499,  478,  478,  478,  478,  500,
      478,  478,  478,  478,  501,  478,  478,  478,  478,  502,
      478,  478,  478,  478,  503,  478,  478,  478,  478,  504,
      478,  478,  478,  478,  505,  478,  478,  478,  478,  506,
      478,  478,  507,  508,  509,  510,  511,  512,  513,  514,
      515,  516,  517,  518,  519,  520,  521,  522,  523,  524,
      525,  526,  527,  528,  529,  530,  531,  532,  533,  534,
      535,  536,  537,  538,  539,  540,  541,  542,  543,  544,
      545,  546,  547,  548,  549,  550,  551,  552,  553,  554,
      555,  556,  557,  558,  559,  560,  561,  562,  563,  564,

      565,  566,  567,  568,  569,  570,  571,  572,  573,  574,
      575,  576,  577,  578,  579,  580,  581,  582,  583,  584,
      585,  586,  587,  588,  589,  590,  591,  592,  593,  594,
      595,  596,  597,  598,  599,  600,  601,  602,  603,  604,
      605,  606,  607,  608,  609,  610,  611,  612,  613,  614,
      615,  616,  617,  618,  619,  620,  621,  622,  623,  624,
      625,  626,  627,  628,  629,  630,  631,  632,  633,  634,
      635,  636,  637,  638,  639,  640,  641,  642,  643,  644,
      645,  646,  647,  648,  649,  650,  651,  652,  653,  654,
      655,  656,  657,  658,  659,  660,  661,  662,  663,  664,

      665,  666,  667,  668,  669,  670,  671,  672,  673,  674,
      675,  676,  677,  678,  679,  680,  681,  682,  683,  684,
      685,  686,  687,  688,  689,  690,  691,  692,  693,  694,
      695,  696,  697,  698,  699,  700,  701,  702,  703,  704,
      705,  706,  707,  708,  709,  710,  711,  712,  713,  714,
      715,  716,  717,  718,  719,  720,  721,  722,  723,  724,
      725,  726,  727,  728,  729,  730,  731,  732,  733,  734,
      735,  736,  737,  738,  739,  740,  478,    0,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,

      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,

      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,

      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478
    } ;

static yyconst flex_uint16_t yy_nxt[1071] =
    {   0,
        4,    5,    6,    5,    5,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   26,   27,   28,   29,   30,
       26,   31,   32,   33,   26,   34,   35,   26,   26,   36,
       26,   26,   26,   37,   38,   39,   40,   26,   41,   42,
       26,   43,   44,   45,   49,   53,   56,   54,   54,   55,
       55,   59,   66,   60,   75,   67,   58,   71,   49,   76,
       61,   84,   54,  242,   88,   50,   72,   89,   73,   59,
       61,   92,   93,   74,   61,   94,   91,  239,   61,   50,
       54,  117,  115,   59,   61,  118,  237,   54,   61,  137,

      234,   59,   61,  139,   54,   59,  152,  154,  232,   54,
       61,  162,   61,   59,   61,  164,   54,   59,  170,  172,
       61,   54,   61,  176,   61,   59,   61,  178,   54,   59,
      181,  183,   61,   54,   61,  186,   61,   59,   61,  188,
       54,   59,  191,  193,   61,   54,   61,  196,   61,   59,
       61,  198,   54,   59,  201,  203,   61,   54,   61,  206,
       61,   59,   61,  208,   54,   59,  211,  213,   61,   54,
       61,  216,   61,   59,   61,  218,   54,   59,  221,  223,
       61,   54,   61,  226,   61,   59,   61,  228,   54,   59,
      231,  233,   61,   54,   61,  236,   61,   59,   61,  238,

       54,   59,  241,  238,   61,   54,   61,  241,   61,  229,
       61,  227,  224,  222,  219,  217,   61,  214,  212,  209,
       61,   48,   48,   48,   48,   48,   48,   52,   52,   65,
      207,   65,   86,   86,   86,   90,  204,   90,   90,   90,
       90,   95,  202,   95,  112,  112,  112,  112,  112,  112,
      114,  114,  114,  120,  199,  120,  136,  136,  136,  141,
      197,  141,  156,  194,  156,  166,  192,  166,  174,  189,
      174,  180,  187,  180,  185,  184,  185,  190,  182,  190,
      195,  179,  195,  200,  177,  200,  205,  175,  205,  210,
      173,  210,  215,  171,  215,  220,  169,  220,  225,  168,

      225,  230,  167,  230,  235,  165,  235,  240,  163,  240,
      243,  161,  243,  244,  160,  244,  245,  159,  245,  246,
      158,  246,  247,  157,  247,  248,  155,  248,  249,  153,
      249,  250,   85,  250,  251,  151,  251,  252,  150,  252,
      253,  149,  253,  254,  148,  254,  255,  147,  255,  256,
      146,  256,  257,  145,  257,  258,  144,  258,  259,  143,
      259,  260,  142,  260,  261,  140,  261,  262,   91,  262,
      263,  138,  263,  264,   85,  264,  265,  113,  265,  266,
      135,  266,  267,  134,  267,  268,  133,  268,  269,  132,
      269,  270,  131,  270,  271,  130,  271,  272,  129,  272,

      273,  128,  273,  274,  127,  274,  275,  126,  275,  276,
      125,  276,  277,  124,  277,  278,  123,  278,  279,  122,
      279,  280,  121,  280,  281,  119,  281,  282,   94,  282,
      283,   91,  283,  284,  116,  284,  285,   89,  285,  286,
       85,  286,  287,  113,  287,  288,  111,  288,  289,  110,
      289,  290,  109,  290,  291,  108,  291,  292,  107,  292,
      293,  106,  293,  294,  105,  294,  295,  104,  295,  296,
      103,  296,  297,  102,  297,  298,  101,  298,  299,  100,
      299,  300,   99,  300,  301,   98,  301,  302,   97,  302,
      303,   96,  303,  304,   57,  304,  305,   91,  305,  306,

       87,  306,  307,   85,  307,  308,  478,  308,  309,   83,
      309,  310,   82,  310,  311,   81,  311,  312,   80,  312,
      313,   79,  313,  314,   78,  314,  315,   77,  315,  316,
       70,  316,  317,   69,  317,  318,   68,  318,  319,   64,
      319,  320,   63,  320,  321,   62,  321,  322,   58,  322,
      323,   57,  323,  324,   51,  324,  325,   47,  325,  326,
      478,  326,  327,   46,  327,  328,  478,  328,  329,  478,
      329,  330,  478,  330,  331,  478,  331,  332,  478,  332,
      333,  478,  333,  334,  478,  334,  335,  478,  335,  336,
      478,  336,  337,  478,  337,  338,  478,  338,  339,  478,

      339,  340,  478,  340,  341,  478,  341,  342,  478,  342,
      343,  478,  343,  344,  478,  344,  345,  478,  345,  346,
      478,  346,  347,  478,  347,  348,  478,  348,  349,  478,
      349,  350,  478,  350,  351,  478,  351,  352,  478,  352,
      353,  478,  353,  354,  478,  354,  355,  478,  355,  356,
      478,  356,  357,  478,  357,  358,  478,  358,  359,  478,
      359,  360,  478,  360,  361,  478,  361,  362,  478,  362,
      363,  478,  363,  364,  478,  364,  365,  478,  365,  366,
      478,  366,  367,  478,  367,  368,  478,  368,  369,  478,
      369,  370,  478,  370,  371,  478,  371,  372,  478,  372,

      373,  478,  373,  374,  478,  374,  375,  478,  375,  376,
      478,  376,  377,  478,  377,  378,  478,  378,  379,  478,
      379,  380,  478,  380,  381,  478,  381,  382,  478,  382,
      383,  478,  383,  384,  478,  384,  385,  478,  385,  386,
      478,  386,  387,  478,  387,  388,  478,  388,  389,  478,
      389,  390,  478,  390,  391,  478,  391,  392,  478,  392,
      393,  478,  393,  394,  478,  394,  395,  478,  395,  396,
      478,  396,  397,  478,  397,  398,  478,  398,  399,  478,
      399,  400,  478,  400,  401,  478,  401,  402,  478,  402,
      403,  478,  403,  404,  478,  404,  405,  478,  405,  406,

      478,  406,  407,  478,  407,  408,  478,  408,  409,  478,
      409,  410,  478,  410,  411,  478,  411,  412,  478,  412,
      413,  478,  413,  414,  478,  414,  415,  478,  415,  416,
      478,  416,  417,  478,  417,  418,  478,  418,  419,  478,
      419,  420,  478,  420,  421,  478,  421,  422,  478,  422,
      423,  478,  423,  424,  478,  424,  425,  478,  425,  426,
      478,  426,  427,  478,  427,  428,  478,  428,  429,  478,
      429,  430,  478,  430,  431,  478,  431,  432,  478,  432,
      433,  478,  433,  434,  478,  434,  435,  478,  435,  436,
      478,  436,  437,  478,  437,  438,  478,  438,  439,  478,

      439,  440,  478,  440,  441,  478,  441,  442,  478,  442,
      443,  478,  443,  444,  478,  444,  445,  478,  445,  446,
      478,  446,  447,  478,  447,  448,  478,  448,  449,  478,
      449,  450,  478,  450,  451,  478,  451,  452,  478,  452,
      453,  478,  453,  454,  478,  454,  455,  478,  455,  456,
      478,  456,  457,  478,  457,  458,  478,  458,  459,  478,
      459,  460,  478,  460,  461,  478,  461,  462,  478,  462,
      463,  478,  463,  464,  478,  464,  465,  478,  465,  466,
      478,  466,  467,  478,  467,  468,  478,  468,  469,  478,
      469,  470,  478,  470,  471,  478,  471,  472,  478,  472,

      473,  478,  473,  474,  478,  474,  475,  478,  475,  476,
      478,  476,  477,  478,  477,    3,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478
    } ;

static yyconst flex_int16_t yy_chk[1071] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    8,   15,   17,   17,   15,   17,
       15,   20,   31,   20,   36,   31,   46,   35,   48,   36,
       20,   46,   55,  239,   55,    8,   35,   57,   35,   60,
       20,   60,   61,   35,   57,   61,   91,  234,   60,   48,
       88,   91,   88,   92,   57,   92,  232,  115,   60,  115,

      229,  118,   92,  118,  137,  139,  137,  139,  227,  152,
      118,  152,   92,  154,  139,  154,  162,  164,  162,  164,
      118,  170,  154,  170,  139,  172,  164,  172,  176,  178,
      176,  178,  154,  181,  172,  181,  164,  183,  178,  183,
      186,  188,  186,  188,  172,  191,  183,  191,  178,  193,
      188,  193,  196,  198,  196,  198,  183,  201,  193,  201,
      188,  203,  198,  203,  206,  208,  206,  208,  193,  211,
      203,  211,  198,  213,  208,  213,  216,  218,  216,  218,
      203,  221,  213,  221,  208,  223,  218,  223,  226,  228,
      226,  228,  213,  231,  223,  231,  218,  233,  228,  233,

      236,  238,  236,  238,  223,  241,  233,  241,  228,  224,
      238,  222,  219,  217,  214,  212,  233,  209,  207,  204,
      238,  479,  479,  479,  479,  479,  479,  480,  480,  481,
      202,  481,  482,  482,  482,  483,  199,  483,  483,  483,
      483,  484,  197,  484,  485,  485,  485,  485,  485,  485,
      486,  486,  486,  487,  194,  487,  488,  488,  488,  489,
      192,  489,  490,  189,  490,  491,  187,  491,  492,  184,
      492,  493,  182,  493,  494,  179,  494,  495,  177,  495,
      496,  173,  496,  497,  171,  497,  498,  168,  498,  499,
      165,  499,  500,  163,  500,  501,  159,  501,  502,  158,

      502,  503,  157,  503,  504,  155,  504,  505,  153,  505,
      506,  150,  506,  507,  149,  507,  508,  147,  508,  509,
      146,  509,  510,  143,  510,  511,  140,  511,  512,  138,
      512,  513,  136,  513,  514,  135,  514,  515,  132,  515,
      516,  131,  516,  517,  130,  517,  518,  129,  518,  519,
      128,  519,  520,  127,  520,  521,  126,  521,  522,  123,
      522,  523,  121,  523,  524,  119,  524,  525,  117,  525,
      526,  116,  526,  527,  114,  527,  528,  112,  528,  529,
      111,  529,  530,  110,  530,  531,  109,  531,  532,  108,
      532,  533,  107,  533,  534,  106,  534,  535,  105,  535,

      536,  104,  536,  537,  102,  537,  538,  101,  538,  539,
      100,  539,  540,   99,  540,  541,   98,  541,  542,   97,
      542,  543,   96,  543,  544,   94,  544,  545,   93,  545,
      546,   90,  546,  547,   89,  547,  548,   87,  548,  549,
       86,  549,  550,   84,  550,  551,   82,  551,  552,   81,
      552,  553,   80,  553,  554,   79,  554,  555,   78,  555,
      556,   77,  556,  557,   76,  557,  558,   74,  558,  559,
       73,  559,  560,   72,  560,  561,   71,  561,  562,   70,
      562,  563,   69,  563,  564,   68,  564,  565,   67,  565,
      566,   66,  566,  567,   59,  567,  568,   58,  568,  569,

       54,  569,  570,   52,  570,  571,   50,  571,  572,   44,
      572,  573,   42,  573,  574,   41,  574,  575,   40,  575,
      576,   39,  576,  577,   38,  577,  578,   37,  578,  579,
       34,  579,  580,   33,  580,  581,   32,  581,  582,   25,
      582,  583,   24,  583,  584,   23,  584,  585,   19,  585,
      586,   18,  586,  587,   10,  587,  588,    7,  588,  589,
        3,  589,  590,    2,  590,  591,    0,  591,  592,    0,
      592,  593,    0,  593,  594,    0,  594,  595,    0,  595,
      596,    0,  596,  597,    0,  597,  598,    0,  598,  599,
        0,  599,  600,    0,  600,  601,    0,  601,  602,    0,

      602,  603,    0,  603,  604,    0,  604,  605,    0,  605,
      606,    0,  606,  607,    0,  607,  608,    0,  608,  609,
        0,  609,  610,    0,  610,  611,    0,  611,  612,    0,
      612,  613,    0,  613,  614,    0,  614,  615,    0,  615,
      616,    0,  616,  617,    0,  617,  618,    0,  618,  619,
        0,  619,  620,    0,  620,  621,    0,  621,  622,    0,
      622,  623,    0,  623,  624,    0,  624,  625,    0,  625,
      626,    0,  626,  627,    0,  627,  628,    0,  628,  629,
        0,  629,  630,    0,  630,  631,    0,  631,  632,    0,
      632,  633,    0,  633,  634,    0,  634,  635,    0,  635,

      636,    0,  636,  637,    0,  637,  638,    0,  638,  639,
        0,  639,  640,    0,  640,  641,    0,  641,  642,    0,
      642,  643,    0,  643,  644,    0,  644,  645,    0,  645,
      646,    0,  646,  647,    0,  647,  648,    0,  648,  649,
        0,  649,  650,    0,  650,  651,    0,  651,  652,    0,
      652,  653,    0,  653,  654,    0,  654,  655,    0,  655,
      656,    0,  656,  657,    0,  657,  658,    0,  658,  659,
        0,  659,  660,    0,  660,  661,    0,  661,  662,    0,
      662,  663,    0,  663,  664,    0,  664,  665,    0,  665,
      666,    0,  666,  667,    0,  667,  668,    0,  668,  669,

        0,  669,  670,    0,  670,  671,    0,  671,  672,    0,
      672,  673,    0,  673,  674,    0,  674,  675,    0,  675,
      676,    0,  676,  677,    0,  677,  678,    0,  678,  679,
        0,  679,  680,    0,  680,  681,    0,  681,  682,    0,
      682,  683,    0,  683,  684,    0,  684,  685,    0,  685,
      686,    0,  686,  687,    0,  687,  688,    0,  688,  689,
        0,  689,  690,    0,  690,  691,    0,  691,  692,    0,
      692,  693,    0,  693,  694,    0,  694,  695,    0,  695,
      696,    0,  696,  697,    0,  697,  698,    0,  698,  699,
        0,  699,  700,    0,  700,  701,    0,  701,  702,    0,

      702,  703,    0,  703,  704,    0,  704,  705,    0,  705,
      706,    0,  706,  707,    0,  707,  708,    0,  708,  709,
        0,  709,  710,    0,  710,  711,    0,  711,  712,    0,
      712,  713,    0,  713,  714,    0,  714,  715,    0,  715,
      716,    0,  716,  717,    0,  717,  718,    0,  718,  719,
        0,  719,  720,    0,  720,  721,    0,  721,  722,    0,
      722,  723,    0,  723,  724,    0,  724,  725,    0,  725,
      726,    0,  726,  727,    0,  727,  728,    0,  728,  729,
        0,  729,  730,    0,  730,  731,    0,  731,  732,    0,
      732,  733,    0,  733,  734,    0,  734,  735,    0,  735,

      736,    0,  736,  737,    0,  737,  738,    0,  738,  739,
        0,  739,  740,    0,  740,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478,
      478,  478,  478,  478,  478,  478,  478,  478,  478,  478
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.flex"
#line 2 "scanner.flex"
    #include "token.h"
#line 901 "scanner.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

			int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 6 "scanner.flex"

#line 1124 "scanner.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 479 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1016 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 7 "scanner.flex"
/* skip whitespace */
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 8 "scanner.flex"
{ return TOKEN_ARRAY; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 9 "scanner.flex"
{ return TOKEN_BOOLEAN; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 10 "scanner.flex"
{ return TOKEN_CHARACTER; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 11 "scanner.flex"
{ return TOKEN_FLOAT; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 12 "scanner.flex"
{ return TOKEN_INTEGER; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 13 "scanner.flex"
{ return TOKEN_STRING; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 14 "scanner.flex"
{ return TOKEN_FUNCTION; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 15 "scanner.flex"
{ return TOKEN_VOID; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 16 "scanner.flex"
{ return TOKEN_AUTO; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 17 "scanner.flex"
{ return TOKEN_ELSE; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 18 "scanner.flex"
{ return TOKEN_FALSE; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 19 "scanner.flex"
{ return TOKEN_FOR; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 20 "scanner.flex"
{ return TOKEN_IF; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 21 "scanner.flex"
{ return TOKEN_PRINT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 22 "scanner.flex"
{ return TOKEN_RETURN; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 23 "scanner.flex"
{ return TOKEN_TRUE; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 24 "scanner.flex"
{ return TOKEN_WHILE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 25 "scanner.flex"
{ return TOKEN_L_PAREN; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 26 "scanner.flex"
{ return TOKEN_R_PAREN; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 27 "scanner.flex"
{ return TOKEN_L_BRACE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 28 "scanner.flex"
{ return TOKEN_R_BRACE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 29 "scanner.flex"
{ return TOKEN_L_BRACKET; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 30 "scanner.flex"
{ return TOKEN_R_BRACKET; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 31 "scanner.flex"
{ return TOKEN_POSTINC; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 32 "scanner.flex"
{ return TOKEN_POSTDEC; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 33 "scanner.flex"
{ return TOKEN_EXP; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 34 "scanner.flex"
{ return TOKEN_MUL; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 35 "scanner.flex"
{ return TOKEN_DIV; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 36 "scanner.flex"
{ return TOKEN_MOD; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 37 "scanner.flex"
{ return TOKEN_ADD; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 38 "scanner.flex"
{ return TOKEN_SUB; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 39 "scanner.flex"
{ return TOKEN_LE; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 40 "scanner.flex"
{ return TOKEN_GE; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 41 "scanner.flex"
{ return TOKEN_EQUAL; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 42 "scanner.flex"
{ return TOKEN_NEQUAL; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 43 "scanner.flex"
{ return TOKEN_LESS; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 44 "scanner.flex"
{ return TOKEN_GREATER; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 45 "scanner.flex"
{ return TOKEN_AND; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 46 "scanner.flex"
{ return TOKEN_OR; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 47 "scanner.flex"
{ return TOKEN_ASSIGN; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 48 "scanner.flex"
{ return TOKEN_NOT; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 50 "scanner.flex"
{ return TOKEN_SEMICOLON; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 51 "scanner.flex"
{ return TOKEN_COMMA; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 52 "scanner.flex"
{ return TOKEN_COLON; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 53 "scanner.flex"
{ return TOKEN_BACKSLASH; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 56 "scanner.flex"
{ return TOKEN_IDENTIFIER; }
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 58 "scanner.flex"
{ return TOKEN_STRING_LITERAL; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 59 "scanner.flex"
{ return TOKEN_CHARACTER_LITERAL; } /* need post-processing */
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 61 "scanner.flex"
{ return TOKEN_FLOAT_LITERAL; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 62 "scanner.flex"
{ return TOKEN_FLOAT_LITERAL; } /* may match integer section, flex need match int first */
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 64 "scanner.flex"
{ return TOKEN_INTEGER_LITERAL; }
	YY_BREAK
case 53:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 66 "scanner.flex"
{ return TOKEN_CPP_COMMENT; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 67 "scanner.flex"
{return TOKEN_C_COMMENT; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 69 "scanner.flex"
{ return TOKEN_EOF; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 70 "scanner.flex"
{ return TOKEN_ERROR; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 73 "scanner.flex"
ECHO;
	YY_BREAK
#line 1471 "scanner.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,(yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,(yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 479 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 479 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (flex_int16_t) yy_c];
	yy_is_jam = (yy_current_state == 478);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc((yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,(int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 73 "scanner.flex"


int yywrap() {return 1;}
